Car 69 landing page
CarFinder/CarFinderApi pull request #27
Opened 2017-11-15 13:36 UTC by ElizavetaBuraya

2017-11-15 15:45 UTC, synthetiquely approved these changes

2017-11-16 14:21 UTC, BobriK502 approved these changes

2017-11-16 15:02 UTC, AntonNarkevich requested changes
Please fix some issues I commented.
The rest looks really good.

2017-11-16 15:02 UTC, AntonNarkevich commented on spec/landingPage.ts
> +      assert.fail('Test failed. No validation error thrown for wrong username and email format');
This looks amazing! Now we have readable tests :)

2017-11-16 15:02 UTC, AntonNarkevich commented on src/services/userService.ts
> +  } catch (error) {
Do we really need this try-catch block?

2017-11-16 15:02 UTC, AntonNarkevich commented on src/utils/userMessage.ts
> +        global.console.log(`The mail sent to ${mail.auth.user}`);
Wait, why are we using global like that?

2017-11-16 15:02 UTC, AntonNarkevich commented on src/utils/userMessage.ts
> +  if (process.env.NODE_ENV !== 'test') {
Please do if (wrong) {return;} it makes the code readable.

2017-11-16 15:02 UTC, AntonNarkevich commented on src/utils/userMessage.ts
> +export const sendUserEmail = (data: IMessage, action: string): void => {
This function needs to be async.

2017-11-16 15:02 UTC, AntonNarkevich commented on src/utils/userMessage.ts
> +          throw err;
This throw won't work. It happens out of context.

2017-11-16 15:49 UTC, AntonNarkevich requested changes

2017-11-16 15:49 UTC, AntonNarkevich commented on src/utils/userMessage.ts
> +  transport
Why don't we do 'await' here?

2017-11-16 15:49 UTC, AntonNarkevich commented on src/utils/userMessage.ts
> +    .catch(error => {
If we'd do await above we wouldn't need this catch at all.

2017-11-16 15:49 UTC, AntonNarkevich commented on src/utils/userMessage.ts
> +      throw error;
Throwing in catch block.... looks a bit odd.

2017-11-16 16:43 UTC, merged